server:
  port: 6702
spring:
  jackson:
    default-property-inclusion: always
  datasource:
    #url: jdbc:sqlserver://39.104.86.43:1433;DatabaseName=PowerPIPTest_0703
    url: jdbc:sqlserver://10.150.172.49:1433;DatabaseName=PowerPMS20201107
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    #password: P@ssw0rd
    password: Abc-12345
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
  jpa:
    show-sql: true
  resources:
    static-locations:
      - classpath:resources
      - classpath:static
  mvc:
    static-path-pattern: /**
    view:
      prefix: /WEB-INF/
      suffix: .jsp

#是否激活 swagger true or false
swagger:
  enable: true

power:
  epsProjId: 00000000-0000-0000-0000-0000000000a4
  regHumName: 系统管理员
  regHumId: ad000000-0000-0000-0000-000000000000
  ownProjName: 内蒙古察哈尔新能源有限公司
  ownProjId: 00000000-0000-0000-0000-0000000000a4
exam:
  appId: 1
  appKey: 9f08551fa9bf4633b0da3c0b3eaa028a
  #domainUrl: https://api.kaoshixing.com
  domainUrl: http://39.104.110.153
  achievementCode: 702
  longinCode: 201
task:
  corePoolSize: 10
  maxPoolSize: 200
  queueCapacity: 10

sigpdf:
  url: http://sign.kinggrid.com:80/iSignatureServer/OfficeServer.jsp
  key: T001
  password: 123456
  sessionUrl: D:/桌面/

project:
  url: http://127.0.0.1:6702
  ftpUrl: http://127.0.0.1:6703
